# config/database.yml

# 1. DEFAULT SETTINGS (Used by Dev & Test)
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Docker uses 'db', Local uses 'localhost'
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>

# 2. DEVELOPMENT (Local/Docker)
development:
  <<: *default
  database: short_link_development

# 3. TEST (RSpec)
test:
  <<: *default
  database: short_link_test

# 4. PRODUCTION (Render)
# We do NOT use <<: *default here.
# We rely solely on the DATABASE_URL provided by Render.
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
